/**
 * PDF Export utility for simulation reports.
 *
 * Uses jsPDF to generate branded, multi-page simulation reports.
 * The header uses styled text ("InsightForge") — designed to be
 * easily swapped with a logo image in the future.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ── Types ──

interface SimulationPDFData {
  title: string;
  stimulus: string;
  segmentName: string;
  workspaceName?: string;
  // Results
  response: string;
  sentiment: number | null;
  confidence: number | null;
  purchaseIntent?: string;
  emotionalReaction?: string;
  keyThemes?: string[];
  keyDecisionFactors?: string[];
  // Meta
  tokensUsed?: number;
  durationMs?: number;
  createdAt?: string;
}

interface FocusGroupPDFData {
  title: string;
  stimulus: string;
  participantNames: string[];
  workspaceName?: string;
  rounds: Array<{
    round: number;
    responses: Array<{
      segment_name: string;
      response: string;
      sentiment: number;
      confidence: number;
    }>;
  }>;
  aggregate: {
    consensus_score?: number;
    avg_sentiment?: number;
    avg_confidence?: number;
    key_themes?: string[];
  };
  createdAt?: string;
}

// ── Helpers ──

const PRIMARY_COLOR: [number, number, number] = [124, 58, 237]; // Purple-600
const TEXT_COLOR: [number, number, number] = [30, 30, 30];
const MUTED_COLOR: [number, number, number] = [120, 120, 120];

function addHeader(doc: jsPDF, workspaceName?: string) {
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Brand bar ──
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, pageWidth, 28, "F");

  // Logo text (easily replaceable with doc.addImage() for a real logo)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text("InsightForge", 14, 18);

  // Tagline
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(220, 220, 255);
  doc.text("AI Consumer Twin Report", pageWidth - 14, 12, { align: "right" });

  // Date + workspace
  doc.setFontSize(7);
  doc.text(
    `${workspaceName ? workspaceName + " · " : ""}${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    pageWidth - 14,
    20,
    { align: "right" }
  );
}

function addFooter(doc: jsPDF, pageNum: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(7);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(
    `Generated by InsightForge · Page ${pageNum}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );
  doc.setDrawColor(220, 220, 220);
  doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16);
}

function sentimentLabel(s: number | null): string {
  if (s === null) return "N/A";
  if (s > 0.2) return `Positive (${(s > 0 ? "+" : "") + s.toFixed(2)})`;
  if (s < -0.2) return `Negative (${s.toFixed(2)})`;
  return `Neutral (${s.toFixed(2)})`;
}

function confidenceLabel(c: number | null): string {
  if (c === null) return "N/A";
  const pct = Math.round(c * 100) + "%";
  if (c >= 0.8) return `High (${pct})`;
  if (c >= 0.6) return `Medium (${pct})`;
  return `Low (${pct})`;
}

// ── Simulation PDF ──

export function generateSimulationPDF(data: SimulationPDFData): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 38;

  // ── Page 1: Overview ──
  addHeader(doc, data.workspaceName);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Simulation Report", 14, y);
  y += 10;

  // Segment & Title
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(`Segment: ${data.segmentName}`, 14, y);
  y += 6;
  doc.text(`Created: ${data.createdAt || new Date().toISOString().split("T")[0]}`, 14, y);
  y += 10;

  // Stimulus
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Stimulus / Question", 14, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_COLOR);
  const stimulusLines = doc.splitTextToSize(data.stimulus || "N/A", pageWidth - 28);
  doc.text(stimulusLines, 14, y);
  y += stimulusLines.length * 4 + 8;

  // Metrics Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Results Summary", 14, y);
  y += 2;

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Sentiment", sentimentLabel(data.sentiment)],
      ["Confidence", confidenceLabel(data.confidence)],
      ["Purchase Intent", data.purchaseIntent?.replace(/_/g, " ") || "N/A"],
      ["Emotional Reaction", data.emotionalReaction || "N/A"],
      ["Tokens Used", data.tokensUsed?.toLocaleString() || "N/A"],
      ["Duration", data.durationMs ? `${(data.durationMs / 1000).toFixed(1)}s` : "N/A"],
    ],
    theme: "striped",
    headStyles: { fillColor: PRIMARY_COLOR },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 9 },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Consumer Response
  if (y > 220) {
    addFooter(doc, 1);
    doc.addPage();
    addHeader(doc, data.workspaceName);
    y = 38;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Consumer Response", 14, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_COLOR);
  const responseLines = doc.splitTextToSize(data.response || "No response recorded.", pageWidth - 28);
  doc.text(responseLines, 14, y);
  y += responseLines.length * 4 + 8;

  // Key Themes
  if (data.keyThemes?.length) {
    if (y > 240) {
      addFooter(doc, doc.getNumberOfPages());
      doc.addPage();
      addHeader(doc, data.workspaceName);
      y = 38;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEXT_COLOR);
    doc.text("Key Themes", 14, y);
    y += 6;
    data.keyThemes.forEach((theme, i) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED_COLOR);
      doc.text(`${i + 1}. ${theme}`, 18, y);
      y += 5;
    });
    y += 5;
  }

  addFooter(doc, doc.getNumberOfPages());

  // ── Page: Methodology Note ──
  doc.addPage();
  addHeader(doc, data.workspaceName);
  y = 38;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Methodology Note", 14, y);
  y += 10;

  const methodologyText = [
    "This simulation was generated using InsightForge's Digital Consumer Twin technology. The twin is an AI persona anchored in demographic, psychographic, and cultural data specific to the target segment.",
    "",
    "The AI model (Gemini 2.5 Flash) was constraint-prompted with intersectional demographic anchors before generating the response. Temperature scaling was applied based on question type to balance creativity with factual accuracy.",
    "",
    `The confidence score (${confidenceLabel(data.confidence)}) reflects the twin's calibration level, data density, and demographic anchoring quality. Scores ≥ 0.80 indicate high reliability; scores < 0.60 should be treated as exploratory hypotheses.`,
    "",
    "For maximum accuracy, we recommend calibrating this twin with real survey/focus group data via the Validation Dashboard. Each calibration cycle improves future predictions through our autoregressive correction loop.",
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_COLOR);
  methodologyText.forEach(line => {
    if (line === "") {
      y += 3;
    } else {
      const lines = doc.splitTextToSize(line, pageWidth - 28);
      doc.text(lines, 14, y);
      y += lines.length * 4;
    }
  });

  addFooter(doc, doc.getNumberOfPages());

  // Save
  const filename = `insightforge-simulation-${data.segmentName.replace(/\s+/g, "-").toLowerCase()}-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

// ── Focus Group PDF ──

export function generateFocusGroupPDF(data: FocusGroupPDFData): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 38;

  // ── Page 1: Overview ──
  addHeader(doc, data.workspaceName);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Focus Group Report", 14, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(`Participants: ${data.participantNames.join(", ")}`, 14, y);
  y += 6;
  doc.text(`Rounds: ${data.rounds.length}`, 14, y);
  y += 6;
  doc.text(`Created: ${data.createdAt || new Date().toISOString().split("T")[0]}`, 14, y);
  y += 10;

  // Stimulus
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Discussion Topic", 14, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_COLOR);
  const stimLines = doc.splitTextToSize(data.stimulus, pageWidth - 28);
  doc.text(stimLines, 14, y);
  y += stimLines.length * 4 + 8;

  // Aggregate Summary
  if (data.aggregate) {
    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value"]],
      body: [
        ["Consensus Score", data.aggregate.consensus_score != null ? Math.round(data.aggregate.consensus_score * 100) + "%" : "N/A"],
        ["Avg Sentiment", sentimentLabel(data.aggregate.avg_sentiment ?? null)],
        ["Avg Confidence", confidenceLabel(data.aggregate.avg_confidence ?? null)],
      ],
      theme: "striped",
      headStyles: { fillColor: PRIMARY_COLOR },
      margin: { left: 14, right: 14 },
      styles: { fontSize: 9 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  addFooter(doc, 1);

  // ── Rounds Detail ──
  data.rounds.forEach((round, ri) => {
    doc.addPage();
    addHeader(doc, data.workspaceName);
    y = 38;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Round ${round.round}`, 14, y);
    y += 8;

    round.responses.forEach(resp => {
      if (y > 240) {
        addFooter(doc, doc.getNumberOfPages());
        doc.addPage();
        addHeader(doc, data.workspaceName);
        y = 38;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...PRIMARY_COLOR);
      doc.text(resp.segment_name, 14, y);
      y += 5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...MUTED_COLOR);
      doc.text(`Sentiment: ${sentimentLabel(resp.sentiment)} · Confidence: ${confidenceLabel(resp.confidence)}`, 14, y);
      y += 5;

      doc.setFontSize(9);
      doc.setTextColor(...TEXT_COLOR);
      const respLines = doc.splitTextToSize(resp.response, pageWidth - 28);
      doc.text(respLines, 14, y);
      y += respLines.length * 4 + 8;
    });

    addFooter(doc, doc.getNumberOfPages());
  });

  const filename = `insightforge-focus-group-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}
