// Originally auto-generated by Lovable with the project URL + anon key
// hardcoded as constants. That hardcoding was the actual root cause of the
// "Failed to fetch" signup bug — the JS bundle pointed at a dead/inaccessible
// Supabase project regardless of what Vercel env vars said, because env vars
// were never read here.
//
// Now reads from Vite's import.meta.env at build time so the deployed bundle
// matches whatever VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY were set
// when Vercel ran the build. Required for signup, login, and every other
// Supabase call to actually reach the right backend.
//
// Do NOT re-introduce hardcoded fallback URLs here. If the env vars are missing
// the build should fail loudly rather than silently ship a wrong URL.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as
  | string
  | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Crash loudly during dev/build so the missing env var is immediately
  // obvious. In production this would have meant a broken signup flow that
  // ships silently — exactly the bug this file was previously hiding.
  throw new Error(
    "Missing Supabase env vars. Set VITE_SUPABASE_URL and " +
      "VITE_SUPABASE_PUBLISHABLE_KEY in .env (local) and in Vercel " +
      "Project Settings → Environment Variables (Production + Preview)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
